project:
  type: website
  output-dir: docs

website:
  title: "Peter Vitale"
  favicon: images/favicon.png
  navbar:
    title: false
    logo: images/logo.png
    logo-alt: Black oystercatcher coding in R
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - href: CV.qmd
        text: CV
      - icon: github
        href: https://github.com/petervitale910/petervitale910.github.io
  page-footer: 
    left: Copyright 2025, Peter Vitale
    right: 
      - icon: reddit
      

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito

editor: visual

